language: go

notifications:
  email: false

go:
  - "1.12.5"

env:
  - GO111MODULE=on

script:
  - go test ./...
  - GOOS=linux GOARCH=amd64 go build -ldflags "-X main.Commit=${TRAVIS_COMMIT} -X main.Build=$(date +%Y%m%d) -s -w" -o barito-flow-linux
  - GOOS=darwin GOARCH=amd64 go build -ldflags "-X main.Commit=${TRAVIS_COMMIT} -X main.Build=$(date +%Y%m%d) -s -w" -o barito-flow-darwin
# Debug purpose to check deps
  - file barito-flow-linux && file barito-flow-darwin && ldd barito-flow-linux 

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file:
    - barito-flow-linux
    - barito-flow-darwin
  on:
    tags: true
    repo: BaritoLog/barito-flow
    all_branches: true
