version: "3.7"

services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
      - 9300:9300

  kafka:
    image: spotify/kafka # not working on arm
#    image: ghcr.io/clavinjune/kafka # arm enabled
    environment:
      - "ADVERTISED_HOST=kafka"
      - "ADVERTISED_PORT=9092"
    ports:
      - 9092:9092
      - 2181:2181
  redis:
    image: redis:alpine3.16
    ports:
      - 6379:6379
  producer:
    depends_on:
      - kafka
    image: baritolog/barito-flow
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: "producer"
    environment:
      - BARITO_KAFKA_BROKERS=kafka:9092
    ports:
      - 8080:8080
  consumer:
    image: baritolog/barito-flow
    command: "consumer"
    environment:
      - BARITO_PRODUCER_ADDRESS=producer:8080
      - BARITO_KAFKA_BROKERS=kafka:9092
      - BARITO_ELASTICSEARCH_URLS=http://es:9200
    ports:
      - 9090:8080
    depends_on:
      - producer
      - es
