// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/timber.proto

package timber

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import any "github.com/golang/protobuf/ptypes/any"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Timber struct {
	Context              *TimberContext       `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Content              map[string]*any.Any  `protobuf:"bytes,3,rep,name=content,proto3" json:"content,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Timber) Reset()         { *m = Timber{} }
func (m *Timber) String() string { return proto.CompactTextString(m) }
func (*Timber) ProtoMessage()    {}
func (*Timber) Descriptor() ([]byte, []int) {
	return fileDescriptor_timber_8020021605342346, []int{0}
}
func (m *Timber) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Timber.Unmarshal(m, b)
}
func (m *Timber) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Timber.Marshal(b, m, deterministic)
}
func (dst *Timber) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Timber.Merge(dst, src)
}
func (m *Timber) XXX_Size() int {
	return xxx_messageInfo_Timber.Size(m)
}
func (m *Timber) XXX_DiscardUnknown() {
	xxx_messageInfo_Timber.DiscardUnknown(m)
}

var xxx_messageInfo_Timber proto.InternalMessageInfo

func (m *Timber) GetContext() *TimberContext {
	if m != nil {
		return m.Context
	}
	return nil
}

func (m *Timber) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Timber) GetContent() map[string]*any.Any {
	if m != nil {
		return m.Content
	}
	return nil
}

type TimberCollection struct {
	Context              *TimberContext `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Items                []*Timber      `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *TimberCollection) Reset()         { *m = TimberCollection{} }
func (m *TimberCollection) String() string { return proto.CompactTextString(m) }
func (*TimberCollection) ProtoMessage()    {}
func (*TimberCollection) Descriptor() ([]byte, []int) {
	return fileDescriptor_timber_8020021605342346, []int{1}
}
func (m *TimberCollection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimberCollection.Unmarshal(m, b)
}
func (m *TimberCollection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimberCollection.Marshal(b, m, deterministic)
}
func (dst *TimberCollection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimberCollection.Merge(dst, src)
}
func (m *TimberCollection) XXX_Size() int {
	return xxx_messageInfo_TimberCollection.Size(m)
}
func (m *TimberCollection) XXX_DiscardUnknown() {
	xxx_messageInfo_TimberCollection.DiscardUnknown(m)
}

var xxx_messageInfo_TimberCollection proto.InternalMessageInfo

func (m *TimberCollection) GetContext() *TimberContext {
	if m != nil {
		return m.Context
	}
	return nil
}

func (m *TimberCollection) GetItems() []*Timber {
	if m != nil {
		return m.Items
	}
	return nil
}

type TimberContext struct {
	KafkaTopic             string   `protobuf:"bytes,1,opt,name=kafka_topic,json=kafkaTopic,proto3" json:"kafka_topic,omitempty"`
	KafkaPartition         int32    `protobuf:"varint,2,opt,name=kafka_partition,json=kafkaPartition,proto3" json:"kafka_partition,omitempty"`
	KafkaReplicationFactor int32    `protobuf:"varint,3,opt,name=kafka_replication_factor,json=kafkaReplicationFactor,proto3" json:"kafka_replication_factor,omitempty"`
	EsIndexPrefix          string   `protobuf:"bytes,4,opt,name=es_index_prefix,json=esIndexPrefix,proto3" json:"es_index_prefix,omitempty"`
	EsDocumentType         string   `protobuf:"bytes,5,opt,name=es_document_type,json=esDocumentType,proto3" json:"es_document_type,omitempty"`
	AppMaxTps              int32    `protobuf:"varint,6,opt,name=app_max_tps,json=appMaxTps,proto3" json:"app_max_tps,omitempty"`
	AppSecret              string   `protobuf:"bytes,7,opt,name=app_secret,json=appSecret,proto3" json:"app_secret,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *TimberContext) Reset()         { *m = TimberContext{} }
func (m *TimberContext) String() string { return proto.CompactTextString(m) }
func (*TimberContext) ProtoMessage()    {}
func (*TimberContext) Descriptor() ([]byte, []int) {
	return fileDescriptor_timber_8020021605342346, []int{2}
}
func (m *TimberContext) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimberContext.Unmarshal(m, b)
}
func (m *TimberContext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimberContext.Marshal(b, m, deterministic)
}
func (dst *TimberContext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimberContext.Merge(dst, src)
}
func (m *TimberContext) XXX_Size() int {
	return xxx_messageInfo_TimberContext.Size(m)
}
func (m *TimberContext) XXX_DiscardUnknown() {
	xxx_messageInfo_TimberContext.DiscardUnknown(m)
}

var xxx_messageInfo_TimberContext proto.InternalMessageInfo

func (m *TimberContext) GetKafkaTopic() string {
	if m != nil {
		return m.KafkaTopic
	}
	return ""
}

func (m *TimberContext) GetKafkaPartition() int32 {
	if m != nil {
		return m.KafkaPartition
	}
	return 0
}

func (m *TimberContext) GetKafkaReplicationFactor() int32 {
	if m != nil {
		return m.KafkaReplicationFactor
	}
	return 0
}

func (m *TimberContext) GetEsIndexPrefix() string {
	if m != nil {
		return m.EsIndexPrefix
	}
	return ""
}

func (m *TimberContext) GetEsDocumentType() string {
	if m != nil {
		return m.EsDocumentType
	}
	return ""
}

func (m *TimberContext) GetAppMaxTps() int32 {
	if m != nil {
		return m.AppMaxTps
	}
	return 0
}

func (m *TimberContext) GetAppSecret() string {
	if m != nil {
		return m.AppSecret
	}
	return ""
}

type ProduceResult struct {
	Topic                string   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProduceResult) Reset()         { *m = ProduceResult{} }
func (m *ProduceResult) String() string { return proto.CompactTextString(m) }
func (*ProduceResult) ProtoMessage()    {}
func (*ProduceResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_timber_8020021605342346, []int{3}
}
func (m *ProduceResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProduceResult.Unmarshal(m, b)
}
func (m *ProduceResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProduceResult.Marshal(b, m, deterministic)
}
func (dst *ProduceResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProduceResult.Merge(dst, src)
}
func (m *ProduceResult) XXX_Size() int {
	return xxx_messageInfo_ProduceResult.Size(m)
}
func (m *ProduceResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ProduceResult.DiscardUnknown(m)
}

var xxx_messageInfo_ProduceResult proto.InternalMessageInfo

func (m *ProduceResult) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func init() {
	proto.RegisterType((*Timber)(nil), "timber.Timber")
	proto.RegisterMapType((map[string]*any.Any)(nil), "timber.Timber.ContentEntry")
	proto.RegisterType((*TimberCollection)(nil), "timber.TimberCollection")
	proto.RegisterType((*TimberContext)(nil), "timber.TimberContext")
	proto.RegisterType((*ProduceResult)(nil), "timber.ProduceResult")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProducerServiceClient is the client API for ProducerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProducerServiceClient interface {
	Produce(ctx context.Context, in *Timber, opts ...grpc.CallOption) (*ProduceResult, error)
	ProduceBatch(ctx context.Context, in *TimberCollection, opts ...grpc.CallOption) (*ProduceResult, error)
}

type producerServiceClient struct {
	cc *grpc.ClientConn
}

func NewProducerServiceClient(cc *grpc.ClientConn) ProducerServiceClient {
	return &producerServiceClient{cc}
}

func (c *producerServiceClient) Produce(ctx context.Context, in *Timber, opts ...grpc.CallOption) (*ProduceResult, error) {
	out := new(ProduceResult)
	err := c.cc.Invoke(ctx, "/timber.ProducerService/Produce", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *producerServiceClient) ProduceBatch(ctx context.Context, in *TimberCollection, opts ...grpc.CallOption) (*ProduceResult, error) {
	out := new(ProduceResult)
	err := c.cc.Invoke(ctx, "/timber.ProducerService/ProduceBatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProducerServiceServer is the server API for ProducerService service.
type ProducerServiceServer interface {
	Produce(context.Context, *Timber) (*ProduceResult, error)
	ProduceBatch(context.Context, *TimberCollection) (*ProduceResult, error)
}

func RegisterProducerServiceServer(s *grpc.Server, srv ProducerServiceServer) {
	s.RegisterService(&_ProducerService_serviceDesc, srv)
}

func _ProducerService_Produce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Timber)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProducerServiceServer).Produce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/timber.ProducerService/Produce",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProducerServiceServer).Produce(ctx, req.(*Timber))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProducerService_ProduceBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TimberCollection)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProducerServiceServer).ProduceBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/timber.ProducerService/ProduceBatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProducerServiceServer).ProduceBatch(ctx, req.(*TimberCollection))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProducerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "timber.ProducerService",
	HandlerType: (*ProducerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Produce",
			Handler:    _ProducerService_Produce_Handler,
		},
		{
			MethodName: "ProduceBatch",
			Handler:    _ProducerService_ProduceBatch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/timber.proto",
}

func init() { proto.RegisterFile("proto/timber.proto", fileDescriptor_timber_8020021605342346) }

var fileDescriptor_timber_8020021605342346 = []byte{
	// 484 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x4f, 0x8f, 0xd3, 0x30,
	0x10, 0xc5, 0xd5, 0x96, 0x76, 0xd5, 0xe9, 0xf6, 0x8f, 0xac, 0x05, 0x99, 0x20, 0xd8, 0x55, 0xc5,
	0x9f, 0x8a, 0x43, 0x8a, 0x8a, 0x90, 0x2a, 0x2e, 0x08, 0x16, 0x90, 0x38, 0x20, 0x55, 0xd9, 0xde,
	0x23, 0xd7, 0x9d, 0x2e, 0x56, 0x93, 0xd8, 0xb2, 0x9d, 0x55, 0x72, 0xe7, 0xa3, 0xf0, 0x31, 0x39,
	0xa0, 0xd8, 0xc9, 0xee, 0xb6, 0x88, 0x03, 0xb7, 0xf8, 0xbd, 0x9f, 0xe7, 0xcd, 0x64, 0x0c, 0x44,
	0x69, 0x69, 0xe5, 0xdc, 0x8a, 0x74, 0x83, 0x3a, 0x74, 0x07, 0xd2, 0xf3, 0xa7, 0xe0, 0xf1, 0xb5,
	0x94, 0xd7, 0x09, 0xce, 0x9d, 0xba, 0xc9, 0x77, 0x73, 0x96, 0x95, 0x1e, 0x09, 0xce, 0x8f, 0x2d,
	0x2b, 0x52, 0x34, 0x96, 0xa5, 0xca, 0x03, 0xd3, 0xdf, 0x2d, 0xe8, 0xad, 0x5d, 0x19, 0x32, 0x87,
	0x13, 0x2e, 0x33, 0x8b, 0x85, 0xa5, 0xad, 0x8b, 0xd6, 0x6c, 0xb0, 0x78, 0x18, 0xd6, 0x71, 0x1e,
	0xb8, 0xf4, 0x66, 0xd4, 0x50, 0x64, 0x09, 0xfd, 0xdb, 0x72, 0xb4, 0xed, 0xae, 0x04, 0xa1, 0x0f,
	0x0c, 0x9b, 0xc0, 0xea, 0xae, 0x27, 0xa2, 0x3b, 0x98, 0xbc, 0xab, 0xa3, 0x32, 0x4b, 0x3b, 0x17,
	0x9d, 0xd9, 0x60, 0xf1, 0xe4, 0x30, 0x2a, 0xbc, 0xf4, 0xee, 0x97, 0xcc, 0xea, 0x32, 0x6a, 0xd8,
	0x60, 0x05, 0xa7, 0xf7, 0x0d, 0x32, 0x81, 0xce, 0x1e, 0x4b, 0xd7, 0x6d, 0x3f, 0xaa, 0x3e, 0xc9,
	0x6b, 0xe8, 0xde, 0xb0, 0x24, 0xc7, 0xba, 0x9d, 0xb3, 0xbf, 0xda, 0xf9, 0x98, 0x95, 0x91, 0x47,
	0xde, 0xb7, 0x97, 0xad, 0xa9, 0x80, 0x49, 0x33, 0x5c, 0x92, 0x20, 0xb7, 0x42, 0x66, 0xff, 0xff,
	0x1f, 0x9e, 0x43, 0x57, 0x58, 0x4c, 0x0d, 0x6d, 0xbb, 0x59, 0x46, 0x87, 0x78, 0xe4, 0xcd, 0xe9,
	0xaf, 0x36, 0x0c, 0x0f, 0x0a, 0x90, 0x73, 0x18, 0xec, 0xd9, 0x6e, 0xcf, 0x62, 0x2b, 0x95, 0xe0,
	0xf5, 0x18, 0xe0, 0xa4, 0x75, 0xa5, 0x90, 0x57, 0x30, 0xf6, 0x80, 0x62, 0xda, 0x8a, 0xaa, 0x39,
	0x37, 0x57, 0x37, 0x1a, 0x39, 0x79, 0xd5, 0xa8, 0x64, 0x09, 0xd4, 0x83, 0x1a, 0x55, 0x22, 0x38,
	0xab, 0xc4, 0x78, 0xc7, 0xb8, 0x95, 0x9a, 0x76, 0xdc, 0x8d, 0x47, 0xce, 0x8f, 0xee, 0xec, 0xaf,
	0xce, 0x25, 0x2f, 0x61, 0x8c, 0x26, 0x16, 0xd9, 0x16, 0x8b, 0x58, 0x69, 0xdc, 0x89, 0x82, 0x3e,
	0x70, 0x7d, 0x0c, 0xd1, 0x7c, 0xab, 0xd4, 0x95, 0x13, 0xc9, 0x0c, 0x26, 0x68, 0xe2, 0xad, 0xe4,
	0x79, 0x8a, 0x99, 0x8d, 0x6d, 0xa9, 0x90, 0x76, 0x1d, 0x38, 0x42, 0xf3, 0xb9, 0x96, 0xd7, 0xa5,
	0x42, 0xf2, 0x0c, 0x06, 0x4c, 0xa9, 0x38, 0x65, 0x45, 0x6c, 0x95, 0xa1, 0x3d, 0x17, 0xdf, 0x67,
	0x4a, 0x7d, 0x67, 0xc5, 0x5a, 0x19, 0xf2, 0x14, 0xa0, 0xf2, 0x0d, 0x72, 0x8d, 0x96, 0x9e, 0xb8,
	0x1a, 0x95, 0x7d, 0xe5, 0x84, 0xe9, 0x0b, 0x18, 0xae, 0xb4, 0xdc, 0xe6, 0x1c, 0x23, 0x34, 0x79,
	0x62, 0xc9, 0x19, 0x74, 0xef, 0xff, 0x1f, 0x7f, 0x58, 0xfc, 0x6c, 0xc1, 0xb8, 0xe6, 0xf4, 0x15,
	0xea, 0x1b, 0xc1, 0x91, 0xbc, 0x81, 0x93, 0x5a, 0x22, 0x47, 0x3b, 0x08, 0x6e, 0x57, 0x78, 0x58,
	0xfb, 0x03, 0x9c, 0xd6, 0xc2, 0x27, 0x66, 0xf9, 0x0f, 0x42, 0x8f, 0x37, 0xdd, 0x3c, 0x8a, 0x7f,
	0x14, 0xd8, 0xf4, 0xdc, 0xc3, 0x7a, 0xfb, 0x27, 0x00, 0x00, 0xff, 0xff, 0x84, 0xfa, 0x86, 0x20,
	0x9f, 0x03, 0x00, 0x00,
}
